"""added title column to youtube

Revision ID: 3e2e98ad04ad
Revises: 710c54ff28d9
Create Date: 2026-08-27 02:26:34.246362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2e98ad04ad'
down_revision: Union[str, Sequence[str], None] = '710c54ff28d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tourdates', 'tickets_state',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('users_slug_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    op.add_column('youtube', sa.Column('title', sa.String(length=200), nullable=True))
    op.alter_column('youtube', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('youtube', 'title')
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=False)
    op.create_unique_constraint(op.f('users_slug_key'), 'users', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('tourdates', 'tickets_state',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
