"""add merch items variants and reservations

Revision ID: a11676007713
Revises: 33aea57b079a
Create Date: 2026-09-02 23:52:32.465098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11676007713'
down_revision: Union[str, Sequence[str], None] = '33aea57b079a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merch_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('clothing', 'misc', name='merch_type'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merch_items_id'), 'merch_items', ['id'], unique=False)
    op.create_index(op.f('ix_merch_items_user_id'), 'merch_items', ['user_id'], unique=False)
    op.create_table('merch_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merch_item_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('xs', 's', 'm', 'l', 'xl', 'xxl', name='merch_size'), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merch_item_id'], ['merch_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merch_variants_id'), 'merch_variants', ['id'], unique=False)
    op.create_index(op.f('ix_merch_variants_merch_item_id'), 'merch_variants', ['merch_item_id'], unique=False)
    op.create_table('merch_reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merch_variant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_instagram', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'contacted', 'fulfilled', 'cancelled', name='reservation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merch_variant_id'], ['merch_variants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merch_reservations_id'), 'merch_reservations', ['id'], unique=False)
    op.create_index(op.f('ix_merch_reservations_merch_variant_id'), 'merch_reservations', ['merch_variant_id'], unique=False)
    op.create_index(op.f('ix_merch_reservations_user_id'), 'merch_reservations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merch_reservations_user_id'), table_name='merch_reservations')
    op.drop_index(op.f('ix_merch_reservations_merch_variant_id'), table_name='merch_reservations')
    op.drop_index(op.f('ix_merch_reservations_id'), table_name='merch_reservations')
    op.drop_table('merch_reservations')
    op.drop_index(op.f('ix_merch_variants_merch_item_id'), table_name='merch_variants')
    op.drop_index(op.f('ix_merch_variants_id'), table_name='merch_variants')
    op.drop_table('merch_variants')
    op.drop_index(op.f('ix_merch_items_user_id'), table_name='merch_items')
    op.drop_index(op.f('ix_merch_items_id'), table_name='merch_items')
    op.drop_table('merch_items')
    # ### end Alembic commands ###
